steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/networksecurity-ml/networksecurity-ml-image:$SHORT_SHA"
      - "."

  # Step 2: Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/networksecurity-ml/networksecurity-ml-image:$SHORT_SHA"

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "networksecurity-ml"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/networksecurity-ml/networksecurity-ml-image:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "3"
      - "--set-secrets"
      - "GOOGLE_APPLICATION_CREDENTIALS=sa-key:latest"

# Timeout (optional)
timeout: "1200s"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/networksecurity-ml/networksecurity-ml-image:$SHORT_SHA"
